name: Manual workflow


on:
# push:
 #   branches:
 #   - main
  workflow_dispatch:                                                                                                                 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
     
      - name: Build and push
        run: |
          docker build . --file Dockerfile --tag=helloworld:1.0
          #docker run -d -p 8080:8080 helloworld:1.0
         
  web_app_defn:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      hello-world:
        image: helloworld:1.0
        ports:
          - 8080:8080

    steps:
      - run: apt-get update; apt-get install curl -y
      - run: curl hello-world:8080 > curl_result_docker
      - run: cat curl_result_docker   
               
              
              
              
               
