name: Manual workflow


on:

  workflow_dispatch:                                                                                                                 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
     
      - name: Build and push
        run: |
          docker build . --file Dockerfile --tag=helloworld:1.0
          docker tag helloworld:1.0  krkumar1405.jfrog.io/docker-trial/helloworld
          docker login -urajuharshu@gmail.com krkumar1405.jfrog.io -p Harshu@11
          docker push krkumar1405.jfrog.io/docker-trial/helloworld
          #docker run -d -p 8080:8080 helloworld:1.0
         
  application_check:
    runs-on: ubuntu-latest
    container:
      image: krkumar1405.jfrog.io/docker-trial/helloworld
      credentials:
        username: rajuharshu@gmail.com
        password: Harshu@11
        
      ports:
         - 8080
    steps:
      - name: curl_image
        run: |
          nohup sh -c /usr/local/tomcat/bin/catalina.sh run &
          sleep 20
          ls /usr/local/tomcat/webapps
          curl http://localhost:8080
         
         
        
    

       
