name: Manual workflow


on:
# push:
 #   branches:
 #   - main
  workflow_dispatch:                                                                                                                 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Build and push
        run: |
          docker build . --file Dockerfile --tag=helloworld:1.0
          
          
          docker run -d -p 8080:8080 helloworld:1.0 catalina.sh run
          
          curl -v http://localhost:8080  
