name: Manual workflow


on:
# push:
 #   branches:
 #   - main
  workflow_dispatch:                                                                                                                 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
     
      - name: Build and push
        run: |
          docker build . --file Dockerfile --tag=helloworld:1.0
          docker tag helloworld:1.0  krkumar1405.jfrog.io/docker-trial/helloworld
          docker login -urajuharshu@gmail.com krkumar1405.jfrog.io -p Harshu@11
          docker push krkumar1405.jfrog.io/docker-trial/helloworld
          #docker run -d -p 8080:8080 helloworld:1.0
         
 
               
              
              
              
               
