name: Manual workflow


on:
# push:
 #   branches:
 #   - main
  workflow_dispatch:                                                                                                                 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
     
      - name: Build and push
        run: |
          docker build . --file Dockerfile --tag=helloworld:1.0
          
      - uses: addnab/docker-run-action@v3
        with:
             image: helloworld:1.0
             shell: bash
             run: |  
               pwd
               ls
               jar -xvf webapps/hello-world-war-1.0.0.war
               
               curl localhost:8080/hello-world-war-1.0.0
               
