name: Manual workflow


on:

  workflow_dispatch:                                                                                                                 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
     
      - name: Build and push
        run: |
          docker build . --file Dockerfile --tag=hello-world:2.0
          docker tag hello-world:2.0  krkumar1405.jfrog.io/docker-trial/hello-world
          docker login -urajuharshu@gmail.com krkumar1405.jfrog.io -p Harshu@11
          docker push krkumar1405.jfrog.io/docker-trial/hello-world
          #docker run -d -p 8080:8080 hello-world:1.0
         
  application_check:
    runs-on: ubuntu-latest
    container:
      image: krkumar1405.jfrog.io/docker-trial/hello-world
      credentials:
        username: rajuharshu@gmail.com
        password: Harshu@11
        
      ports:
         - 8080
    steps:
      - name: curl_image
        run: |
          nohup sh /usr/local/tomcat/bin/catalina.sh run &
          sleep 30
          ls /usr/local/tomcat/webapps
          curl -v http://localhost:8080/hello
         
         
        
    

       
